name = "M_CLI2"
version = "0.1.0"
license = "Public Domain"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John S. Urban"

[library]
source-dir="src"

# unit test program

[[test]]   name="runTests"                 source-dir="test"                     main="main.f90"

# demo programs

[[executable]]   name="demo1"  source-dir="PROGRAMS/demo1"  main="demo1.f90"
[[executable]]   name="demo2"  source-dir="PROGRAMS/demo2"  main="demo2.f90"
[[executable]]   name="demo3"  source-dir="PROGRAMS/demo3"  main="demo3.f90"
[[executable]]   name="demo4"  source-dir="PROGRAMS/demo4"  main="demo4.f90"
[[executable]]   name="demo5"  source-dir="PROGRAMS/demo5"  main="demo5.f90"
[[executable]]   name="demo6"  source-dir="PROGRAMS/demo6"  main="demo6.f90"
[[executable]]   name="demo7"  source-dir="PROGRAMS/demo7"  main="demo7.f90"

# sample programs extracted from manpages:

[[executable]] name="demo_get_args_fixed_size"   source-dir="PROGRAMS/demos/get_args_fixed_size" main="get_args_fixed_size.f90"
[[executable]] name="demo_get_args_fixed_length" source-dir="PROGRAMS/demos/get_args_fixed_length" main="get_args_fixed_length.f90"
[[executable]] name="demo_get_args"              source-dir="PROGRAMS/demos/get_args"  main="get_args.f90"
[[executable]] name="demo_set_args"              source-dir="PROGRAMS/demos/set_args"  main="set_args.f90"
[[executable]] name="demo_M_CLI2"                source-dir="PROGRAMS/demos/M_CLI2"    main="M_CLI2.f90"
