name = "M_CLI2"
version = "0.1.0"
license = "Public Domain"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John S. Urban"
description = "Unix-style commandline parsing using a prototype command  (STD:f2008)"

# unit test program
test = [ { name="runTests", source-dir="test", main="main.f90" } ]

# demo programs
executable = [
   { name="demo1", source-dir="demos/demo1", main="demo1.f90" },
   { name="demo2", source-dir="demos/demo2", main="demo2.f90" },
   { name="demo3", source-dir="demos/demo3", main="demo3.f90" },
   { name="demo4", source-dir="demos/demo4", main="demo4.f90" },
   { name="demo5", source-dir="demos/demo5", main="demo5.f90" },
   { name="demo6", source-dir="demos/demo6", main="demo6.f90" },
   { name="demo7", source-dir="demos/demo7", main="demo7.f90" },
   { name="demo8", source-dir="demos/demo8", main="demo8.f90" },
   { name="demo9", source-dir="demos/demo9", main="demo9.f90" },
   { name="get_args_fixed_size", source-dir="demos/demos/get_args_fixed_size", main="get_args_fixed_size.f90" },
   { name="get_args_fixed_length", source-dir="demos/demos/get_args_fixed_length", main="get_args_fixed_length.f90" },
   { name="get_args", source-dir="demos/demos/get_args", main="get_args.f90" },
   { name="set_args", source-dir="demos/demos/set_args", main="set_args.f90" },
   { name="M_CLI2",  source-dir="demos/demos/M_CLI2",  main="M_CLI2.f90" }
]

[library]
source-dir="src"


# sample programs extracted from manpages:
